version: '3'

services:
  unified-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
        SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
        SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
        APP_JWTSECRET: ${APP_JWTSECRET}
        APP_JWTEXPIRATIONINMS: ${APP_JWTEXPIRATIONINMS}
    ports:
      - "8080:8080"
    env_file:
      - .env
