# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Manually install JDK 21
      run: |
        wget -q https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.tar.gz
        sudo tar -xzf jdk-21_linux-x64_bin.tar.gz -C /opt
        sudo update-alternatives --install /usr/bin/java java /opt/jdk-21/bin/java 1
    - name: Verify Java Version
      run: java -version
    - name: Check file permissions
      run: ls -la ./backend/gradlew
    - name: Make gradlew executable
      run: chmod +x ./backend/gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build
